export const particularCategory = {
  id: 1,
  image: require("../../assets/images/Carpenter.jpeg"),
  title: "Carpenter",
  rating: 4.9,
  bookings: "3.4M",
};

export const popularServices = [
  {
    id: 1,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Frequently Booked",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 2,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Balcony",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 3,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Bed",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 4,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Cupboard",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 5,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Door",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 6,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Drill and Hang",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 7,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Furniture Repair",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 8,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "T.V",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
  {
    id: 9,
    image: require("../../assets/images/Furniture_Assembly.jpeg"),
    title: "Window and Curtain",
    services: [
      {
        id: 1,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
      {
        id: 2,
        image: require("../../assets/images/Ac_Repair.png"),
        title: "AC Service and Repair",
        rating: 4.9,
        reviews: "12.5K",
        price: "₹1,000",
        duration: "15 mins",
        offers: [{ title: "₹100 off" }],
        otherInfo: "Installation of one wall decor item",
      },
    ],
  },
];

export const individualService = {
  id: 1,
  image: require("../../assets/images/Individual_Service.jpeg"),
  title: "Full arms + full legs + underarms waxing",
  rating: 4.9,
  reviews: "12.4K",
  bookings: "3.4M",
  services: [
    {
      id: 1,
      image: require("../../assets/images/Ac_Repair.png"),
      title: "Chocolate Roll-On",
      price: "₹100",
      duration: "15 mins",
      reviews: "12.5K",
      rating: 4.9,
      description: [
        "Lorem ipsum dolor sit amet. At repellendus recusandae qui dolores tempora sed illo alias est dolores itaque",
        "Lorem ipsum dolor sit amet. At repellendus recusandae qui dolores tempora ",
      ],
    },
    {
      id: 2,
      image: require("../../assets/images/Ac_Repair.png"),
      title: "Chocolate Roll-On",
      price: "₹100",
      duration: "15 mins",
      reviews: "12.5K",
      rating: 4.9,
      description: [
        "Lorem ipsum dolor sit amet. At repellendus recusandae qui dolores tempora sed illo alias est dolores itaque",
        "Lorem ipsum dolor sit amet. At repellendus recusandae qui dolores tempora ",
      ],
    },
  ],
  workingSteps: [
    {
      id: 1,
      title: "Pre-wax preparation",
      description:
        "Sanitisation of products and body parts followed by pre-wax gel & talcum powder application",
      image: require("../../assets/images/Individual_Service.jpeg"),
    },
    {
      id: 2,
      title: "Waxing",
      description:
        "Sanitisation of products and body parts followed by pre-wax gel & talcum powder application",
      image: require("../../assets/images/Individual_Service.jpeg"),
    },
    {
      id: 3,
      title: "Cleaning Lotion",
      description:
        "Sanitisation of products and body parts followed by pre-wax gel ",
      image: require("../../assets/images/Individual_Service.jpeg"),
    },
    {
      id: 4,
      title: "Postwax Oil",
      description:
        "Sanitisation of products and body parts followed by pre-wax gel & talcum powder application",
      image: require("../../assets/images/Individual_Service.jpeg"),
    },
  ],
  careTips: [
    {
      id: 1,
      description: "Moisturise your skin for soothing effect",
      isDone: true,
    },
    {
      id: 2,
      description:
        "Avoid using chemical products (perfume, scrub, etc) for 2-3 days",
      isDone: false,
    },
    {
      id: 3,
      description: "Do not shower immediately with warm/hot water.",
      isDone: false,
    },
  ],
  faqs: [
    {
      id: 1,
      question: "What is the warranty on the service?",
      answer: "Installation of one wall decor item",
    },
    {
      id: 2,
      question: "What is the warranty on the service?",
      answer: "Installation of one wall decor item",
    },
    {
      id: 3,
      question: "What is the warranty on the service?",
      answer: "Installation of one wall decor item",
    },
    {
      id: 4,
      question: "What is the warranty on the service?",
      answer: "Installation of one wall decor item",
    },
    {
      id: 5,
      question: "What is the warranty on the service?",
      answer: "Installation of one wall decor item",
    },
  ],
  customerReviews: [
    {
      id: 1,
      name: "John Doe",
      rating: 4.5,
      review:
        "The service was good. The technician was on time and did a good job.",
      date: "May 2023",
      profileImage: require("../../assets/images/Profile_Image.jpg"),
    },
    {
      id: 2,
      name: "John Doe",
      rating: 4.5,
      review:
        "The service was good. The technician was on time and did a good job.",
      date: "May 2023",
      profileImage: require("../../assets/images/Profile_Image.jpg"),
    },
    {
      id: 3,
      name: "John Doe",
      rating: 4.5,
      review:
        "The service was good. The technician was on time and did a good job.",
      date: "May 2023",
      profileImage: require("../../assets/images/Profile_Image.jpg"),
    },
  ],
};